version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - prometheus-grafana-network
    extra_hosts:
      - "host.docker.internal:host-gateway"#localhost에서는 extrahost를 추가해줘야함.

  # 추가
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: root
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
    networks:
      - prometheus-grafana-network
    depends_on:
      - prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"#localhost에서는 extrahost를 추가해줘야함.
networks:
  prometheus-grafana-network:

